FEAT :crud service service-package
TruongThiNgocTuyetB1910172/pet-shop pull request #9
Opened 2023-08-03 11:27 UTC by TruongThiNgocTuyetB1910172

2023-08-04 04:19 UTC, voduchuy2001 commented
@TruongThiNgocTuyetB1910172 Hình giao diện đâu comment vô đây

2023-08-04 04:22 UTC, voduchuy2001 requested changes

2023-08-04 04:22 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/ServicePackageController.php
> +        }
selling_price đâu sao không làm

2023-08-04 04:22 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/ServicePackageController.php
> +        }
update có mà create không có là sao

2023-08-04 04:42 UTC, TruongThiNgocTuyetB1910172 commented on app/Http/Controllers/Admin/ServicePackageController.php
> +        }
có nhe cha coi k kĩ

2023-08-04 04:48 UTC, TruongThiNgocTuyetB1910172 commented
![image](https://github.com/TruongThiNgocTuyetB1910172/pet-shop/assets/108908354/a4cb9c5c-14bf-4210-a4d3-9969f2059dc2)
![image](https://github.com/TruongThiNgocTuyetB1910172/pet-shop/assets/108908354/7b043f66-dce9-47f9-bb97-693e39e10125)
![image](https://github.com/TruongThiNgocTuyetB1910172/pet-shop/assets/108908354/c406abb5-bc8e-4f5c-a041-0d00ded85f75)

2023-08-04 04:58 UTC, voduchuy2001 commented
@TruongThiNgocTuyetB1910172  form login/register/forgot-password đâu

2023-08-04 06:12 UTC, TruongThiNgocTuyetB1910172 commented
![image](https://github.com/TruongThiNgocTuyetB1910172/pet-shop/assets/108908354/55eba92a-084c-4708-8901-98b22a8c15af)
![image](https://github.com/TruongThiNgocTuyetB1910172/pet-shop/assets/108908354/3c4fe70c-ee35-4918-ae00-b8c229a66a9e)

2023-08-04 06:14 UTC, TruongThiNgocTuyetB1910172 commented
![image](https://github.com/TruongThiNgocTuyetB1910172/pet-shop/assets/108908354/42939d44-adb3-483a-bad0-5dbf51a8e80f)
![image](https://github.com/TruongThiNgocTuyetB1910172/pet-shop/assets/108908354/7335ad61-83a4-41a4-8419-4da1424f7293)

2023-08-12 05:12 UTC, voduchuy2001 requested changes

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AnimalDetailController.php
> +    }
camel

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AnimalDetailController.php
> +            'variant' => $data['variant'],
remove query()

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AnimalDetailController.php
> +
camel

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AppointmentController.php
> +    }
camel

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AppointmentController.php
> +        return redirect('appointments');
camel

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/ServiceController.php
>      }
camel

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/ServiceController.php
>          toast('Thêm mới dịch vụ ' . $services->name .' thành công','success');
camel

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Requests/AnimalDeatil/CreateAnimalDetailRequest.php
> +        ];
animal_id type?
what is variant in this case ???

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Requests/AnimalDeatil/UpdateAnimalDetailRequest.php
> +        ];
check create request

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Requests/Appointment/CreateAppointmentRequest.php
> +            'notes' => ['nullable'],
type of status
and check camel

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Requests/Appointment/UpdateAppointmentRequest.php
> +            'appointment_at' => ['required', 'after:' . Carbon::now()],
likr create request

2023-08-12 05:12 UTC, voduchuy2001 commented on app/Http/Requests/Profile/UpdateProfileRequest.php
> +    }
remove this file if not use

2023-08-12 05:13 UTC, voduchuy2001 commented
@TruongThiNgocTuyetB1910172 fix review

2023-08-17 10:18 UTC, voduchuy2001 requested changes

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AnimalDetailController.php
>      }
camel

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AnimalDetailController.php
>      }
camel

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AnimalDetailController.php
camel

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/ServiceController.php
> +        return view('admin.services.create',compact('animal_details','services'));
camel

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/VariantServiceController.php
> +
camel

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/VariantServiceController.php
> +
camel

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/VariantServiceController.php
> +        toast('Them thanh cong', 'success');
Tiếng anh hay việt

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/VariantServiceController.php
> +
có xài không

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/CartController.php
> +        return view('client.carts.index',compact('carts'));
camel

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/CartController.php
> +
tiếng anh hay việt

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/CartController.php
> +
tiếng anh hay việt

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/CartController.php
> +
lấy cart của người dùng đang đăng nhập

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/CartController.php
> +       toast('Cap nhat so luong vào giỏ hàng thành công','success');
tiếng anh hay việt

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/CartController.php
> +
tiếng anh hay việt

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/ClientController.php
> +
xóa bớt

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/ProductContronller.php
> +            toast('Sản phẩm đã có trong giỏ hàng.','warning');
user_id hay userId
product_id hay productId

2023-08-17 10:18 UTC, voduchuy2001 commented on app/Http/Controllers/Client/ServiceContronller.php
>          return view('client.service.list',compact('services'));
camel

2023-08-23 04:48 UTC, voduchuy2001 requested changes

2023-08-23 04:48 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/AppointmentController.php
camel

2023-08-23 04:48 UTC, voduchuy2001 commented on app/Http/Controllers/Admin/CategoryController.php
> +            toast('Xóa sản phẩm thuộc danh mục trước khi xóa danh mục !!', 'warning');
sai cách viết tiếng việt

2023-08-23 04:53 UTC, merged